### ISSUE TITLE
File parameter doesn't work for Release job

### ISSUE THREAD

**Issue by JonathanLefebvre** [CircleCI-Public/github-cli-orb#20]
## What happened:

While configuring the workflow. I notice no matter what I do or inject in `files` I have always the message : `stat  /tmp/workspace/artifacts/dist.zip: no such file or director`

Here is the extraction of my config.yml
```
jobs:
      - app_build:
          filters:
            branches:
              only:
                - master
      - github-cli/release:
          pre-steps:
            - *attach_workspace
            - run: 
                command: |
                  ls -la /tmp/workspace/artifacts
          context:
            - GITHUB_CREDS
          tag: << pipeline.git.branch >>-<< pipeline.number >>-dev
          title: << pipeline.git.branch >>-<< pipeline.number >>-dev
          prerelease: true
          files: /tmp/workspace/artifacts/dist.zip  # <-- This doesn't work
          requires:
            - app_build
          filters:
            branches:
              only:
                - master
```

`/tmp/workspace/` come from my workspace attachment. with the folder `artifacts` created by `app_build`

## Expected behavior:
`files` should be able to find a file from anywhere
If the `ls` in `pre-step` can see the file, so should the release task.

output of `ls`
```
#!/bin/bash -eo pipefail
ls -la /tmp/workspace/artifacts

total 62900
drwxr-xr-x 2 circleci circleci       22 Dec 29 20:06 .
drwx------ 3 circleci circleci       23 Dec 29 20:06 ..
-rw-r--r-- 1 circleci circleci 64409035 Dec 29 20:06 dist.zip
CircleCI received exit code 0
```

## Additional Information:
From my code, you can see I have a workspace between both jobs

I found the workaround by doing the `post-steps` and uploading the artifact after the release is created
```
jobs:
      - app_build:
          filters:
            branches:
              only:
                - master
      - github-cli/release:
          pre-steps:
            - *attach_workspace
            - run: 
                command: |
                  ls -la /tmp/workspace/artifacts
          context:
            - GITHUB_CREDS
          tag: << pipeline.git.branch >>-<< pipeline.number >>-dev
          title: << pipeline.git.branch >>-<< pipeline.number >>-dev
          prerelease: true
          post-steps:
            - run:
                command: |
                  gh release upload << pipeline.git.branch >>-<< pipeline.number >>-dev /tmp/workspace/artifacts/dist.zip
          requires:
            - app_build
          filters:
            branches:
              only:
                - master
```
