### ISSUE TITLE
Error running gh/release 

### ISSUE THREAD

**Issue by motionsuggests** [CircleCI-Public/github-cli-orb#21]
## What happened:

When trying to use this orb with our GitHub Enterprise instance and only running `gh/release` it errors out calling 
`gh auth setup-git --hostname "$PARAM_GH_HOSTNAME"`. 

I get the following error: 

```bash
Authenticating GH CLI
You are not logged into the GitHub host "**REDACTED**"

Exited with code exit status 1
```

```yaml
      - gh/release:
          context:
            - GITHUB_CREDS
          hostname: ***********
          filters:
            branches:
              only:
                - main
          notes-file: CHANGELOG.md
          requires:
            - prep_vars
          tag: ${VERSION}
          title: ${VERSION}
```

## Expected behavior:

I think just running `gh/release` should only run `install` not `setup`. 

## Additional Information:

**Related Issue** https://github.com/CircleCI-Public/github-cli-orb/issues/9
