### ISSUE TITLE
Failed to install `github-cli` because of missing additional/required dependencies

### ISSUE THREAD

**Issue by HandsomeCoder** [CircleCI-Public/github-cli-orb#51]
## Orb version:
2.3.0

## What happened:

Failed to install `github-cli` because of missing additional/required dependencies

```
Downloading the GitHub CLI from "https://github.com/cli/cli/releases/download/v2.40.1/gh_2.40.1_linux_amd64.deb"...
Installing the GitHub CLI...
+ apt install ./gh-cli.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'gh' instead of './gh-cli.deb'
The following additional packages will be installed:
  git git-man less libcbor0 liberror-perl libfido2-1 openssh-client patch
Suggested packages:
  gettext-base git-daemon-run | git-daemon-sysvinit git-doc git-el git-email
  git-gui gitk gitweb git-cvs git-mediawiki git-svn keychain libpam-ssh
  monkeysphere ssh-askpass ed diffutils-doc
The following NEW packages will be installed:
  gh git git-man less libcbor0 liberror-perl libfido2-1 openssh-client patch
0 upgraded, 9 newly installed, 0 to remove and 25 not upgraded.
Need to get 8653 kB/20.0 MB of archives.
After this operation, 86.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
+ set +x
Something went wrong installing the GH CLI. Please try again or open an issue.

Exited with code exit status 1
```
![image](https://github.com/CircleCI-Public/github-cli-orb/assets/18287082/8848b7e2-0dc2-4956-ab1c-be8ddc1e222c)

## `config.yml` to reproduce the issue

```
version: 2.1
orbs:
  github-cli: circleci/github-cli@2.3.0

jobs:
  cypress:
    docker:
      - image: cypress/browsers:node16.14.0-chrome99-ff97
    steps:
      - checkout
      - github-cli/setup

workflows:
  samplei:
    jobs:
      - cypress

```

## Expected behavior:

`setup` command should install all the additional/required dependencies

## Additional Information:

Just by adding `--yes` flag at below line: https://github.com/CircleCI-Public/github-cli-orb/blob/e89b4c51027a6659a54235d0d3358f7ff1145494/src/scripts/install.sh#L55 should fix the issue as `apt` will automatically install all the dependencies
