### ISSUE TITLE
Use a more recent default version for GH CLI

### ISSUE THREAD

**Issue by f-belliard** [CircleCI-Public/github-cli-orb#53]
## Describe Request:

GH CLI 2.40.1 is 6 month old and missing some interesting features.
We should update it to the latest.

**Comment by cdong8812** [comment]
Based on the source code, I believe you can override default version 2.40.1 by defining parameter version in your job
```
 install:
   description: Install the gh cli without authenticating or configuring. This command should be run before invoking the gh cli.
     parameters:
         version:
            default: 2.40.1
            description: Specify the full semver versioned tag to use.
            type: string
```
