### ISSUE TITLE
gh/setup failing with sh: 0: unknown operand /bin/sh: syntax error: bad substitution

### ISSUE THREAD

**Issue by adborden** [CircleCI-Public/github-cli-orb#7]
## Orb version:

1.0.3

## What happened:

I'm trying to combine the github-cli and terraform orbs to publish the terraform plan to the GitHub PR. I'm using `gh/setup` with the default `GITHUB_TOKEN` set, but the job fails with the error:
```
sh: 0: unknown operand
/bin/sh: syntax error: bad substitution
```

CircleCI config looks like this:

```yaml
version: '2.1'
orbs:
  terraform: circleci/terraform@2.1.0
  gh: circleci/github-cli@1.0.3
jobs:
  plan:
    executor: terraform/default
    working_directory: terraform
    steps:
      - checkout
      - gh/setup
      - terraform/install
      - terraform/init
      - terraform/fmt:
          recursive: true
      - terraform/validate
      - run: terraform plan -out plan.tfplan
      - run: terraform show plan.tfplan | gh pr comment --body-file -

workflows:
  version: 2
  plan:
    jobs:
      - plan
```

## Expected behavior:

gh/setup should succeed, installing the gh cli OR an actionable error message is reported (e.g. `bash` is not installed).

## Additional Information:

I wonder if there is a mismatch with bash/sh in the terraform executor (or bash might not be available).

I was able to work-around this by using a different image:
```yaml
jobs:
  plan:
    docker:
      - image: cimg/base:stable
 ```
