### ISSUE TITLE
Add support for GitHub Enterprise 

### ISSUE THREAD

**Issue by motionsuggests** [CircleCI-Public/github-cli-orb#9]
## Describe Request:
We would like to use this orb with our GitHub Enterprise instance.  Seems like all that needs to be added is a param for 
`--hostname` and update the script file. 

I'm gonna try to get a PR in for this. 🤞 

## Examples:
```
- gh/setup:
          context:
            - GITHUB_CREDS
          hostname: enterprisehostname
```

## Supporting Documentation Links:
GitHub cli docs for login https://cli.github.com/manual/gh_auth_login
